---
# Fichier requirements.yml
# Liste des rôles Galaxy à installer
roles:
  - name: geerlingguy.docker
    version: "7.4.4"
  - name: geerlingguy.git
    version: "3.0.0"
  - name: geerlingguy.pip
    version: "2.2.0"

collections:
  - name: community.docker
    version: ">=3.0.0"
  - name: community.postgresql
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
